services:
  importer:
    image: ghcr.io/saadbruno/firefly-importer:latest
    build:
      context: .
    container_name: firefly-importer
    restart: unless-stopped
    init: true
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./watch:/app/watch
      - ./parsed:/app/parsed
