services:
  importer:
    image: saadbruno/firefly-importer:latest
    build:
      context: .
    restart: unless-stopped
    init: true
    env_file:
      - .env
    ports:
      - "${HTTP_HOST_PORT:-3000}:${HTTP_PORT:-3000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./watch:/app/watch
      - ./parsed:/app/parsed
